server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        # 💡 1. 일반 유저 로그인!
        index  user-login.html; 
        
        # 💡 2. 일반 유저 로그인! (파일을 못 찾을 때의 기본값)
        try_files $uri $uri/ /user-login.html; 
    }

    # 백엔드 API 프록시 설정 (나중에 EKS에서 경로 찢을 때 참고)
    # location /api/admin {
    #    proxy_pass http://admin-backend:8000;
    # }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}